### ISSUE TITLE
Update to work with Storyscript 0.3.0

### ISSUE THREAD

**Issue by Vesuvium** [asyncy/platform-engine#112]
Hi, I added the ability to import stories in Storyscript 0.3.0. There are changes to how Storyscript compiles imported stories:

- Imported stories will be inside the `stories` object
- An `entrypoint` property is added to root to indicate the starting story
- Each story will have an additional `modules` object, defining which modules where imported by that story

For example:

```coffee
import 'extra.story' as Extra

alpine echo message:x
```

See the imported story and the bundle entrypoint:
```json
{
  "stories": {
    "extra.story": {},
    "hello.story": {}
  },
  "services": [],
  "entrypoint": "hello.story"
}
```

See the modules object:

```json
"hello.story": {
      "tree": {},
      "services": [],
      "entrypoint": "1",
      "modules": {
        "Extra": "extra.story"
      },
      "functions": {},
      "version": "0.3.0"
}
```

**Comment by judepereira** [comment]
@Vesuvium Doesn't `entrypoint` need to be an array? There might be multiple stories which need to be executed, independently:
```json
 "entrypoint": ["hello.story", "hello1.story"]
```

**Comment by Vesuvium** [comment]
Yes, make it an array. I'll update in Storyscript
