### ISSUE TITLE
Docker image size is far too large

### ISSUE THREAD

**Issue by judepereira** [asyncy/platform-engine#122]

**Comment by judepereira** [comment]
Closing, python:3.6.6-stretch is 900MB itself.

**Comment by stevepeak** [comment]
Checkout https://hub.docker.com/r/jfloff/alpine-python/ -- 99MB

If we use this image we should fork it and make a version at `asyncy/python-alpine`

**Comment by judepereira** [comment]
Is it a good idea to run this on musl libc? Although fairly stable, at times when issues arise, they're very hard to debug.

**Comment by stevepeak** [comment]
Honestly, I have not idea about musl libc...
