### ISSUE TITLE
Add strict type checking

### ISSUE THREAD

**Issue by judepereira** [asyncy/platform-engine#130]
When the argument map is created, the data type for each argument is not validated: https://github.com/asyncy/platform-engine/blob/2173fd7c7fbee8c683e8649d86baa71347e26366/asyncy/processing/Services.py#L197-L200

If `args` has a key called `type`, it must be validated appropriately. List of possible data types can be found here: https://microservice.guide/schema/actions/

**Comment by rewop** [comment]
The link https://microservice.guide/commands/#types is not found.
I believe this is the link https://microservice.guide/schema/actions/

**Comment by judepereira** [comment]
@rewop Oh yes, that is the updated link.
