### ISSUE TITLE
Disallow nested streaming blocks

### ISSUE THREAD

**Issue by judepereira** [asyncy/platform-engine#191]
Stories like the following may exhibit undesired behaviour, and is best to detect and stop their execution:
```coffee
slack ... as bot
  websocket accept path:'/' as ws
      when ws.message as client
          foo = client.data.foo
          when bot.listen filter:foo as event
             foo ...
```

**Comment by stevepeak** [comment]
Should be caught at compile time. I can see this being necessary in the future, but for now I'm ok with disabling it.

**Comment by wilzbach** [comment]
PR for Storyscript to detect this at compile time: https://github.com/storyscript/storyscript/pull/761

**Comment by judepereira** [comment]
Perfect, closing this since it's caught already.
