### ISSUE TITLE
Deploying in maintenance mode waits forever

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-engine#236]
When your application is in maintenance mode then you deploy; the CLI will wait forever.

**Steps to reproduce** 
1. `asyncy maintenance on`
1. `asyncy deploy`
3. You will now see `Waiting for deployment to complete...` forever.

> Turning off maintenance mode, then re-deploying works, as expected 👍

**Comment by judepereira** [comment]
Closed with https://github.com/asyncy/cli/pull/112.
