### ISSUE TITLE
Data mutation bindings

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-engine#60]
> Syntax for Storyscript at asyncy/storyscript#120

The Engine will handle data mutation without using containers for obvious performance reasons.

Let's start with some basics.

## String
- Split `"a,b,c" split "," == ["a", "b", "c"]`
- Replace `"foobar" replace before:"bar" after:"cat" == "foocat"`
- Length `"foobar" length == 6`
- Lower `"FooBar" lowercase == 'foobar'`
- Uper `"FooBar" uppercas == 'FOOBAR'`
- Capitalize `"fOO bAR" capitalize == 'Foo Bar'`

> Not on reasonable to map all the basic python string mutations

## Lists
- Join `["a", "b"] join "+" == "a+b"`
- Index `["a", "b"] index "b" == 1`
- Reverse `["a", "b"] reverse == ["b", "a"]`

## Object
- Keys `{"key": "value"} keys == ["key"]`
- Values `{"key": "value"} values == ["value"]`
- Remove `{"a": "b", "c": "d"} remove "a" == {"c": "d"}`

**Comment by judepereira** [comment]
Implement execution as per https://github.com/asyncy/storyscript/issues/150#issuecomment-398454580
