### ISSUE TITLE
Variable storage policy

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-engine#71]
A queued process i.e., cron/http-endpoint/wait/pubsub/pause/etc. require variables to persist until the story is resumed. Variables may be shared by multiple holding processes. Variables that are declared before a holding process are global to that operation and any other that share that variable.

```coffee
n = 0

http-endpoint path:'/' as request, response
    response write message:"The new number is {{n}}"

every seconds:1
    n increment
    not_global = null
```
> The variable `n` is mutated in the `every` process which is reflected in the http `response`.

## Alpha
Variables are stored in-memory (since one Engine during Alpha)

## Beta
Variables are cached and persisted, not in memory, so they can shared across multiple Engines for the same app.

**Comment by judepereira** [comment]
Closing in favour of triggering events with delays.
